<?php

namespace App\Repository;

/**
 * ApartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLimit($limit)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a
                 FROM App:Apartment a
                 ORDER BY a.id ASC'
            )->setMaxResults($limit);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function getRandom($limit)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a
                 FROM App:Apartment a'
            );

        try {

            // dirty, but I don't give a fuck #thuglife
            $results = $query->getResult();
            shuffle($results);
            return array_slice($results,0,$limit);

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function finByCountry($country)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a
                 FROM App:Apartment a
                 WHERE a.country = :selectedCountry
                 ORDER BY a.buildyear ASC'
            )->setParameter('selectedCountry',$country);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
