ApartmentList:
    type: object
    config:
        description: "A query to return list of Apartments"
        fields:
            id:
                type: "String!"
                description: "The unique hash of the attendee query params."
            apartments:
                type: "[Apartment]"
                description: "Apartment details"