Query:
    type: object
    config:
        description: "Apartments ORM repository"
        fields:
            apartment:
                type: "Apartment"
                args:
                    id:
                        description: "Resolves using the attendee id."
                        type: "Int"
                resolve: "@=resolver('Attendee', [args])"
            attendee_list:
                type: "AttendeeList"
                args:
                    limit:
                        description: "limit"
                        type: "Int"
                resolve: "@=resolver('AttendeeList', [args])"